apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-storagecluster-ceph-rbd
